# 7_mission_dashboard/report_generator.py
"""Generates a PDF mission report (summary, delta-V, GA result) from module 2/3 data."""
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
import datetime


def generate_mission_report(mission_spec, constraint_report, ga_result, filepath):
    doc = SimpleDocTemplate(filepath, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("AstroEvo Mission Report", styles["Title"]))
    story.append(Paragraph(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M UTC')}", styles["Normal"]))
    story.append(Spacer(1, 20))

    story.append(Paragraph("Mission Summary", styles["Heading2"]))
    summary_rows = [
        ["Mission", mission_spec.name],
        ["Origin radius (km)", f"{mission_spec.r1:.1f}"],
        ["Destination radius (km)", f"{mission_spec.r2:.1f}"],
        ["Delta-V required (km/s)", f"{constraint_report['dv_total_kms']:.4f}"],
        ["Departure burn (km/s)", f"{constraint_report['dv1_kms']:.4f}"],
        ["Arrival burn (km/s)", f"{constraint_report['dv2_kms']:.4f}"],
        ["Transfer time (hr)", f"{constraint_report['transfer_time_hr']:.2f}"],
        ["Propellant mass fraction", f"{constraint_report['propellant_mass_fraction']:.4f}"],
        ["Feasible", "YES" if constraint_report["feasible"] else "NO"],
    ]
    if not constraint_report["feasible"]:
        summary_rows.append(["Violations", ", ".join(constraint_report["violations"])])

    table = Table(summary_rows, colWidths=[2.5 * inch, 3 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#4C72B0")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (1, 0), (1, -1), [colors.whitesmoke, colors.white]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(table)
    story.append(Spacer(1, 20))

    if ga_result is not None:
        story.append(Paragraph("Trajectory Optimization (Genetic Algorithm)", styles["Heading2"]))
        best_gene = ga_result["best_gene"]
        best_info = ga_result["best_info"]
        ga_rows = [
            ["Best transfer angle (deg)", f"{best_gene[0]:.2f}"],
            ["Best time-of-flight (hr)", f"{best_gene[1]:.2f}"],
            ["GA delta-V (km/s)", f"{best_info['dv_total_kms']:.4f}"],
            ["Feasible", "YES" if best_info["feasible"] else "NO"],
        ]
        ga_table = Table(ga_rows, colWidths=[2.5 * inch, 3 * inch])
        ga_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#DD8452")),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (1, 0), (1, -1), [colors.whitesmoke, colors.white]),
        ]))
        story.append(ga_table)
        story.append(Spacer(1, 20))

    story.append(Paragraph(
        "Generated by AstroEvo - all figures computed live from module 2 (mission planner) "
        "and module 3 (genetic optimizer); not pre-filled.", styles["Normal"]
    ))

    doc.build(story)
    return filepath