# 15_edge_inference/export_weights.py
"""
Trains the lander's PPO ActorCritic network (module 4) briefly, then
exports its weights as a plain C header (static const float arrays) -
no pickle, no numpy, no Python runtime needed to USE the resulting
model. This is the concrete first step toward "Edge-AI Ready On-Board
Autonomy": proving the trained policy's actual numbers can be loaded
and run by a few hundred lines of portable C, the kind of thing that
compiles for an ARM Cortex-M/R OBC or any other embedded target.

HONEST SCOPE: this exports float32 weights and compiles/runs natively
on this machine (x86) via gcc to PROVE numeric correctness vs. the
Python/numpy policy. It does NOT cross-compile for ARM, does NOT
quantize to int8, and has NOT been run on real embedded hardware.
Those are the next concrete steps, not yet done here.
"""
import sys
import os
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "4_neural_controller"))
from lunar_lander_env import LunarLanderEnv, STATE_DIM, N_ACTIONS
from ppo_agent import PPOAgent, normalize_state, STATE_SCALE


def export_to_c_header(net, path):
    def fmt_array(name, arr):
        flat = np.asarray(arr, dtype=np.float32).flatten()
        vals = ", ".join(f"{v:.8e}f" for v in flat)
        shape_comment = "x".join(str(d) for d in np.asarray(arr).shape)
        return f"// shape: {shape_comment}\nstatic const float {name}[{len(flat)}] = {{{vals}}};\n"

    lines = [
        "// Auto-generated by export_weights.py - DO NOT EDIT BY HAND.",
        "// Trained PPO ActorCritic weights for the lunar lander policy (module 4).",
        f"#define STATE_DIM {net.W1.shape[0]}",
        f"#define HIDDEN_DIM {net.W1.shape[1]}",
        f"#define ACTION_DIM {net.W2.shape[1]}",
        "",
        fmt_array("STATE_SCALE", STATE_SCALE),
        fmt_array("W1", net.W1),   # STATE_DIM x HIDDEN_DIM
        fmt_array("B1", net.b1),   # HIDDEN_DIM
        fmt_array("W2", net.W2),   # HIDDEN_DIM x ACTION_DIM
        fmt_array("B2", net.b2),   # ACTION_DIM
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    env = LunarLanderEnv(seed=1)
    agent = PPOAgent(state_dim=STATE_DIM, action_dim=N_ACTIONS, hidden=32,
                      lr=0.005, gamma=0.99, lam=0.95, clip_eps=0.2,
                      epochs=4, minibatch_size=64, seed=2)

    iterations = int(os.environ.get("EDGE_EXPORT_ITERATIONS", "100"))  # 100*10=1000 episodes, quick
    agent.train(env, iterations=iterations, episodes_per_rollout=10, verbose_every=max(1, iterations // 5))

    out_path = os.path.join(os.path.dirname(__file__), "model_weights.h")
    export_to_c_header(agent.net, out_path)
    print(f"\nExported trained weights to {out_path}")

    # Also save a numpy copy so the test can load the EXACT same weights
    # for a Python-vs-C numeric cross-check (rather than retraining, which
    # would give a different - though structurally identical - network).
    np.savez(os.path.join(os.path.dirname(__file__), "trained_weights.npz"),
              W1=agent.net.W1, b1=agent.net.b1, W2=agent.net.W2, b2=agent.net.b2)
